fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    vmware_puppetfact: "https://github.com/wolfspyre/vmware_puppetfact.git"
    zypprepo:
      repo: "https://github.com/deadpoint/puppet-zypprepo.git"
      ref: "v1.0.2"
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "4.1.0"
  symlinks:
    vmwaretools: "#{source_dir}"
