fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    vmware_puppetfact: "https://github.com/wolfspyre/vmware_puppetfact.git"
    zypprepo:
      repo: "https://github.com/voxpupuli/puppet-zypprepo.git"
      ref: "v2.2.2"
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "2.4.0"
  symlinks:
    vmwaretools: "#{source_dir}"
